client_id: '364b9776d05d4fdba13999d1958ff032'
client_secret: '1b638f351c5c425491ab0730bc2b4bb7'
access_token_url: 'https://accounts.spotify.com/api/token'
auth_url: 'http://accounts.spotify.com/authorize'
api_version: v1
api_url: 'http://api.spotify.com'
auth_method: 'AUTHORIZATION_CODE'
